### ISSUE TITLE
Support OpenAPI/Swagger Specification Upload for API Product

### ISSUE THREAD

**Issue by robincher** [Kong/terraform-provider-konnect#12] opened 2024-04-19 08:32 UTC
It will be nice to have the capability to upload OpenAPI Specification when creating the API Product, and make the automation flow more complete.

The corresponding Konnect API for spec upload
https://docs.konghq.com/konnect/api/api-products/latest/#/API%20Product%20Version%20Specification/create-api-product-version-spec

**Comment by mheap** [comment] 2024-05-04 18:35
Closing as duplicate of #11

**Closed by mheap** 2024-05-04 18:35 UTC
