### ISSUE TITLE
Unable to "patch" portal

### ISSUE THREAD

**Issue by mark-sivill-kong** [Kong/terraform-provider-konnect#66] opened 2024-08-12 11:23 UTC
Unable to “patch” portal by changing is_public from true to false ( and vice versa )

```
resource "konnect_portal" "example_portal" {
  name                      = "example"
  auto_approve_applications = false
  auto_approve_developers   = false
  is_public                 = true
  rbac_enabled              = false
}

```
 
As will get error

` {"status":409,"title":"Conflict","instance":"kong:trace:8885013084407593231","detail":"name: \"example\" already exists and must be unique."}`

The current workaround is to terraform destroy then apply, not sure if this is a bug or expected behavior

**Comment by mheap** [comment] 2024-08-25 19:09
I've reproduced with the API. It looks like our name conflict detection isn't taking in to account if the name is in use by the portal that we're updating. I've flagged internally

**Comment by mheap** [comment] 2024-09-11 15:31
This is resolved in the API - no provider update needed

**Closed by mheap** 2024-09-11 15:31 UTC
Labels: blocked:internal
