### ISSUE TITLE
Add more list options for objects

### ISSUE THREAD

**Issue by mark-sivill-kong** [Kong/terraform-provider-konnect#65] opened 2024-08-12 11:20 UTC
Currently, only portal objects can list entities i.e.

```
data "konnect_portal_list" "hundred_portals" {
  page_size   = 100
  page_number = 1
}
```

Please add support for control planes, gateway services, etc.

This will help identify gateway services defined with deck to be tied with API Product Versions defined with Terraform

**Comment by mheap** [comment] 2024-11-12 11:03
Closing as a duplicate of #10

**Closed by mheap** 2024-11-12 11:03 UTC
Labels: blocked:generator
