### ISSUE TITLE
Datasource for e.g. a Control Plane to fetch its Id by name

### ISSUE THREAD

**Issue by lcsn** [Kong/terraform-provider-konnect#79] opened 2024-09-17 07:35 UTC
Hey Michael, thank you for taking your time working on the konnect provider. It would be nice having a datasource to fetch the id of a control plane by its name. This way we could split the configuration into multiple projects like one for rather global or shared configuration and api specific configuration like services, routes and stuff. Currently if the id changes, we manually update referenced variables. Of course this is more of a test or staging environments problem but still would be nice.

**Comment by mheap** [comment] 2024-11-11 09:56
Data sources based on filters such as name are in the works. I'll close this as a duplicate of #10, but we're actively working on this

**Closed** 2024-11-11 09:56 UTC
